//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol1")]
        public string mesin1 {
            get {
                return ((string)(this["mesin1"]));
            }
            set {
                this["mesin1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol2")]
        public string mesin2 {
            get {
                return ((string)(this["mesin2"]));
            }
            set {
                this["mesin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol3")]
        public string mesin3 {
            get {
                return ((string)(this["mesin3"]));
            }
            set {
                this["mesin3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol4")]
        public string mesin4 {
            get {
                return ((string)(this["mesin4"]));
            }
            set {
                this["mesin4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol5")]
        public string mesin5 {
            get {
                return ((string)(this["mesin5"]));
            }
            set {
                this["mesin5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol6")]
        public string mesin6 {
            get {
                return ((string)(this["mesin6"]));
            }
            set {
                this["mesin6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol7")]
        public string mesin7 {
            get {
                return ((string)(this["mesin7"]));
            }
            set {
                this["mesin7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol8")]
        public string mesin8 {
            get {
                return ((string)(this["mesin8"]));
            }
            set {
                this["mesin8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol9")]
        public string mesin9 {
            get {
                return ((string)(this["mesin9"]));
            }
            set {
                this["mesin9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol10")]
        public string mesin10 {
            get {
                return ((string)(this["mesin10"]));
            }
            set {
                this["mesin10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol11")]
        public string mesin11 {
            get {
                return ((string)(this["mesin11"]));
            }
            set {
                this["mesin11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol12")]
        public string mesin12 {
            get {
                return ((string)(this["mesin12"]));
            }
            set {
                this["mesin12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol13")]
        public string mesin13 {
            get {
                return ((string)(this["mesin13"]));
            }
            set {
                this["mesin13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol14")]
        public string mesin14 {
            get {
                return ((string)(this["mesin14"]));
            }
            set {
                this["mesin14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol15")]
        public string mesin15 {
            get {
                return ((string)(this["mesin15"]));
            }
            set {
                this["mesin15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol16")]
        public string mesin16 {
            get {
                return ((string)(this["mesin16"]));
            }
            set {
                this["mesin16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol17")]
        public string mesin17 {
            get {
                return ((string)(this["mesin17"]));
            }
            set {
                this["mesin17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol18")]
        public string mesin18 {
            get {
                return ((string)(this["mesin18"]));
            }
            set {
                this["mesin18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol19")]
        public string mesin19 {
            get {
                return ((string)(this["mesin19"]));
            }
            set {
                this["mesin19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol20")]
        public string mesin20 {
            get {
                return ((string)(this["mesin20"]));
            }
            set {
                this["mesin20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol21")]
        public string mesin21 {
            get {
                return ((string)(this["mesin21"]));
            }
            set {
                this["mesin21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol22")]
        public string mesin22 {
            get {
                return ((string)(this["mesin22"]));
            }
            set {
                this["mesin22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol23")]
        public string mesin23 {
            get {
                return ((string)(this["mesin23"]));
            }
            set {
                this["mesin23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol24")]
        public string mesin24 {
            get {
                return ((string)(this["mesin24"]));
            }
            set {
                this["mesin24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol25")]
        public string mesin25 {
            get {
                return ((string)(this["mesin25"]));
            }
            set {
                this["mesin25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol26")]
        public string mesin26 {
            get {
                return ((string)(this["mesin26"]));
            }
            set {
                this["mesin26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol27")]
        public string mesin27 {
            get {
                return ((string)(this["mesin27"]));
            }
            set {
                this["mesin27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol28")]
        public string mesin28 {
            get {
                return ((string)(this["mesin28"]));
            }
            set {
                this["mesin28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol29")]
        public string mesin29 {
            get {
                return ((string)(this["mesin29"]));
            }
            set {
                this["mesin29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol30")]
        public string mesin30 {
            get {
                return ((string)(this["mesin30"]));
            }
            set {
                this["mesin30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol31")]
        public string mesin31 {
            get {
                return ((string)(this["mesin31"]));
            }
            set {
                this["mesin31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol32")]
        public string mesin32 {
            get {
                return ((string)(this["mesin32"]));
            }
            set {
                this["mesin32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol33")]
        public string mesin33 {
            get {
                return ((string)(this["mesin33"]));
            }
            set {
                this["mesin33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol34")]
        public string mesin34 {
            get {
                return ((string)(this["mesin34"]));
            }
            set {
                this["mesin34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol35")]
        public string mesin35 {
            get {
                return ((string)(this["mesin35"]));
            }
            set {
                this["mesin35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol36")]
        public string mesin36 {
            get {
                return ((string)(this["mesin36"]));
            }
            set {
                this["mesin36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol37")]
        public string mesin37 {
            get {
                return ((string)(this["mesin37"]));
            }
            set {
                this["mesin37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol38")]
        public string mesin38 {
            get {
                return ((string)(this["mesin38"]));
            }
            set {
                this["mesin38"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol39")]
        public string mesin39 {
            get {
                return ((string)(this["mesin39"]));
            }
            set {
                this["mesin39"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tombol40")]
        public string mesin40 {
            get {
                return ((string)(this["mesin40"]));
            }
            set {
                this["mesin40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user")]
        public string Passworduser {
            get {
                return ((string)(this["Passworduser"]));
            }
            set {
                this["Passworduser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1276")]
        public string masteruser {
            get {
                return ((string)(this["masteruser"]));
            }
            set {
                this["masteruser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1276")]
        public string masterpassword {
            get {
                return ((string)(this["masterpassword"]));
            }
            set {
                this["masterpassword"] = value;
            }
        }
    }
}
